# This buildspec is for AWS Codebuild
version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub_ro_username
    DOCKERHUB_PASSWORD: dockerhub_ro_password

phases:
  # pre_build:
  #   commands:
  #     - echo logging in to dockerhub.
  #     - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  install:
    commands:
      - docker version
      - curl -JLO https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-v0.8.2.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - chmod a+rx ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - echo Build started on `date`
      - echo Building and Pushing the Docker image...
      - docker buildx build --cache-from type=registry,ref=$APTOS_VALIDATOR_REPO --cache-to type=registry,ref=$APTOS_VALIDATOR_REPO,mode=max --build-arg GIT_REV="$(git rev-parse HEAD)" --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --tag "$APTOS_VALIDATOR_REPO:dev_$(git rev-parse --short=8  HEAD)" --push --file docker/validator/Dockerfile .
      - echo Build completed on `date`
  # post_build:
  #   commands:
  #     # Tag and push the docker images
  #     - SOURCE=aptos/validator:latest TARGET_REPO=$APTOS_VALIDATOR_REPO TARGET_TAGS="${TAGS}:dev_$(git rev-parse --short=8  HEAD)" docker/tag-and-push.sh
